# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               SumOne Tech Blog
tagline:             Blog técnico da SumOne
url:                 http://sumoners.github.io/
paginate:            10
baseurl:             ""
excerpt_separator:   "<!-- more -->"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Sumoners
  url:               http://www.sumone.com.br
  email:             sumone@sumone.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/sumoners/sumoners.github.io

# Settings for sharing
# Sharing is for things like tweet, plusone, hn upvotes, like, linkedin
# Add a tweet button 		=> provider : tweet
# Add a like button 		=> provider : like (you also need a facebook appid)
# Add a plus one button 	=> provider : plusone
# Add a HN button 		=> provider : hn
# Add them all (i.e. hn + tweet + plusone + like) => provider : all
# Set 'provider' to the sharing provider you want to use.
# Set 'provider' to false to turn sharing off globally.
#
sharing:
  provider: all
  twitter:
    size:
    via: "sumonewizards"
    count:
  facebook:
    appid: 910890595644391
    layout: button_count
    font:
    faces: false
    width: 50
  googleplus:
    size: medium
    width: "50px"
    annotation: bubble
